Started logging messages at Tue May 28 16:04:16 2019
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 2 B-reps in file
Info:    Found 140 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-006
Info:    Working on 0
Info:        Working on 112
Info:            Created 
Info:        Working on 113
Info:            Created 
Info:        Working on 173
Info:            Created 
Info:        Working on 18
Info:            Created 
Info:        Working on 168
Info:            Created 
Info:        Working on 169
Info:            Created 
Info:        Working on 239
Info:            Created 
Info:        Working on 24
Info:            Created 
Info:        Working on 237
Info:            Created 
Info:        Working on 32
Info:            Created 
Info:        Working on 397
Info:            Created 
Info:        Working on 476
Info:            Created 
Info:        Working on 405
Info:            Created 
Info:        Working on 326
Info:            Created 
Info:        Working on 49
Info:            Created 
Info:        Working on 392
Info:            Created 
Info:        Working on 473
Info:            Created 
Info:        Working on 90
Info:            Created 
Info:        Working on 471
Info:            Created 
Info:        Working on 556
Info:            Created 
Info:        Working on 90
Info:            Created 
Info:        Working on 554
Info:            Created 
Info:        Working on 640
Info:            Created 
Info:        Working on 227
Info:            Created 
Info:        Working on 303
Info:            Created 
Info:        Working on 715
Info:            Created 
Info:        Working on 379
Info:            Created 
Info:        Working on 779
Info:            Created 
Info:        Working on 462
Info:            Created 
Info:        Working on 838
Info:            Created 
Info:        Working on 547
Info:            Created 
Info:        Working on 633
Info:            Created 
Info:        Working on 942
Info:            Created 
Info:        Working on 983
Info:            Created 
Info:        Working on 709
Info:            Created 
Info:        Working on 981
Info:            Created 
Info:        Working on 982
Info:            Created 
Info:        Working on 774
Info:            Created 
Info:        Working on 1017
Info:            Created 
Info:        Working on 832
Info:            Created 
Info:        Working on 1048
Info:            Created 
Info:        Working on 1081
Info:            Created 
Info:        Working on 885
Info:            Created 
Info:        Working on 931
Info:            Created 
Info:        Working on 1116
Info:            Created 
Info:        Working on 1150
Info:            Created 
Info:        Working on 973
Info:            Created 
Info:        Working on 1149
Info:            Created 
Info:        Working on 1178
Info:            Created 
Info:        Working on 1010
Info:            Created 
Info:        Working on 1039
Info:            Created 
Info:        Working on 1201
Info:            Created 
Info:        Working on 1167
Info:            Created 
Info:        Working on 1071
Info:            Created 
Info:        Working on 1166
Info:            Created 
Info:        Working on 1245
Info:            Created 
Info:        Working on 1108
Info:            Created 
Info:        Working on 1143
Info:            Created 
Info:        Working on 1263
Info:            Created 
Info:        Working on 1141
Info:            Created 
Info:        Working on 1172
Info:            Created 
Info:        Working on 1139
Info:            Created 
Info:        Working on 1242
Info:            Created 
Info:        Working on 1170
Info:            Created 
Info:        Working on 1198
Info:            Created 
Info:        Working on 1007
Info:            Created 
Info:        Working on 769
Info:            Created 
Info:        Working on 829
Info:            Created 
Info:        Working on 1036
Info:            Created 
Info:        Working on 1068
Info:            Created 
Info:        Working on 881
Info:            Created 
Info:        Working on 924
Info:            Created 
Info:        Working on 439
Info:            Created 
Info:        Working on 439
Info:            Created 
Info:        Working on 439
Info:            Created 
Info:        Working on 439
Info:            Created 
Info:        Working on 868
Info:            Created 
Info:        Working on 869
Info:            Created 
Info:        Working on 863
Info:            Created 
Info:        Working on 805
Info:            Created 
Info:        Working on 867
Info:            Created 
Info:        Working on 1018
Info:            Created 
Info:        Working on 909
Info:            Created 
Info:        Working on 826
Info:            Created 
Info:        Working on 1000
Info:            Created 
Info:        Working on 878
Info:            Created 
Info:        Working on 921
Info:            Created 
Info:        Working on 439
Info:            Created 
Info:        Working on 439
Info:            Created 
Info:        Working on 665
Info:            Created 
Info:        Working on 746
Info:            Created 
Info:        Working on 996
Info:            Created 
Info:        Working on 1026
Info:            Created 
Info:        Working on 816
Info:            Created 
Info:        Working on 896
Info:            Created 
Info:        Working on 897
Info:            Created 
Info:        Working on 852
Info:            Created 
Info:        Working on 851
Info:            Created 
Info:        Working on 871
Info:            Created 
Info:        Working on 1094
Info:            Created 
Info:        Working on 913
Info:            Created 
Info:        Working on 1130
Info:            Created 
Info:        Working on 951
Info:            Created 
Info:        Working on 1162
Info:            Created 
Info:        Working on 990
Info:            Created 
Info:        Working on 1161
Info:            Created 
Info:        Working on 1191
Info:            Created 
Info:        Working on 1021
Info:            Created 
Info:        Working on 1215
Info:            Created 
Info:        Working on 1051
Info:            Created 
Info:        Working on 1238
Info:            Created 
Info:        Working on 1084
Info:            Created 
Info:        Working on 1237
Info:            Created 
Info:        Working on 1258
Info:            Created 
Info:        Working on 1119
Info:            Created 
Info:        Working on 1277
Info:            Created 
Info:        Working on 1153
Info:            Created 
Info:        Working on 1294
Info:            Created 
Info:        Working on 1181
Info:            Created 
Info:        Working on 1293
Info:            Created 
Info:        Working on 1310
Info:            Created 
Info:        Working on 1204
Info:            Created 
Info:        Working on 1326
Info:            Created 
Info:        Working on 1229
Info:            Created 
Info:        Working on 1341
Info:            Created 
Info:        Working on 1248
Info:            Created 
Info:        Working on 1340
Info:            Created 
Info:        Working on 1360
Info:            Created 
Info:        Working on 1266
Info:            Created 
Info:        Working on 1384
Info:            Created 
Info:        Working on 1285
Info:            Created 
Info:        Working on 1410
Info:            Created 
Info:        Working on 1300
Info:            Created 
Info:        Working on 1409
Info:            Created 
Info:        Working on 1443
Info:            Created 
Info:        Working on 1315
Info:            Created 
Info:        Working on 1480
Info:            Created 
Info:        Working on 1332
Info:            Created 
Info:        Working on 1522
Info:            Created 
Info:        Working on 1350
Info:            Created 
Info:        Working on 1521
Info:            Created 
Info:        Working on 1564
Info:            Created 
Info:        Working on 1373
Info:            Created 
Info:        Working on 1607
Info:            Created 
Info:        Working on 1401
Info:            Created 
Info:        Working on 1638
Info:            Created 
Info:        Working on 1433
Info:            Created 
Info:        Working on 1637
Info:            Created 
Info:        Working on 1663
Info:            Created 
Info:        Working on 1469
Info:            Created 
Info:        Working on 1677
Info:            Created 
Info:        Working on 1514
Info:            Created 
Info:        Working on 1610
Info:            Created 
Info:        Working on 1555
Info:            Created 
Info:        Working on 1639
Info:            Created 
Info:        Working on 1687
Info:            Created 
Info:        Working on 1599
Info:            Created 
Info:        Working on 1688
Info:            Created 
Info:        Working on 1632
Info:            Created 
Info:        Working on 1612
Info:            Created 
Info:        Working on 1641
Info:            Created 
Info:        Working on 1575
Info:            Created 
Info:        Working on 1679
Info:            Created 
Info:        Working on 1615
Info:            Created 
Info:        Working on 1681
Info:            Created 
Info:        Working on 1645
Info:            Created 
Info:        Working on 1537
Info:            Created 
Info:        Working on 1580
Info:            Created 
Info:        Working on 1578
Info:            Created 
Info:        Working on 1680
Info:            Created 
Info:        Working on 1618
Info:            Created 
Info:        Working on 1682
Info:            Created 
Info:        Working on 1649
Info:            Created 
Info:        Working on 1539
Info:            Created 
Info:        Working on 1582
Info:            Created 
Info:        Working on 1498
Info:            Created 
Info:        Working on 1654
Info:            Created 
Info:        Working on 1542
Info:            Created 
Info:        Working on 1656
Info:            Created 
Info:        Working on 1586
Info:            Created 
Info:        Working on 1460
Info:            Created 
Info:        Working on 1503
Info:            Created 
Info:        Working on 1501
Info:            Created 
Info:        Working on 1655
Info:            Created 
Info:        Working on 1545
Info:            Created 
Info:        Working on 1657
Info:            Created 
Info:        Working on 1590
Info:            Created 
Info:        Working on 1462
Info:            Created 
Info:        Working on 1505
Info:            Created 
Info:        Working on 1428
Info:            Created 
Info:        Working on 1595
Info:            Created 
Info:        Working on 1465
Info:            Created 
Info:        Working on 1596
Info:            Created 
Info:        Working on 1509
Info:            Created 
Info:        Working on 1398
Info:            Created 
Info:        Working on 1430
Info:            Created 
Info:        Working on 1296
Info:            Created 
Info:        Working on 917
Info:            Created 
Info:        Working on 917
Info:            Created 
Info:        Working on 917
Info:            Created 
Info:        Working on 917
Info:            Created 
Info:        Working on 917
Info:            Created 
Info:        Working on 917
Info:            Created 
Info:        Working on 917
Info:            Created 
Info:        Working on 917
Info:            Created 
Info:        Working on 917
Info:            Created 
Info:        Working on 917
Info:            Created 
Info:        Working on 917
Info:            Created 
Info:        Working on 917
Info:            Created 
Info:        Working on 917
Info:            Created 
Info:        Working on 917
Info:            Created 
Info:        Working on 1297
Info:            Created 
Info:        Working on 1217
Info:            Created 
Info:        Working on 1194
Info:            Created 
Info:        Working on 1219
Info:            Created 
Info:        Working on 1028
Info:            Created 
Info:        Working on 1059
Info:            Created 
Info:        Working on 823
Info:            Created 
Info:        Working on 917
Info:            Created 
Info:        Working on 613
Info:            Created 
Info:        Working on 753
Info:            Created 
Info:        Working on 436
Info:            Created 
Info:        Working on 517
Info:            Created 
Info:        Working on 686
Info:            Created 
Info:        Working on 611
Info:            Created 
Info:        Working on 614
Info:            Created 
Info:        Working on 435
Info:            Created 
Info:        Working on 524
Info:            Created 
Info:        Working on 724
Info:            Created 
Info:        Working on 654
Info:            Created 
Info:        Working on 490
Info:            Created 
Info:        Working on 569
Info:            Created 
Info:        Working on 524
Info:            Created 
Info:        Working on 605
Info:            Created 
Info:        Working on 683
Info:            Created 
Info:        Working on 751
Info:            Created 
Info:        Working on 770
Info:            Created 
Info:        Working on 595
Info:            Created 
Info:        Working on 504
Info:            Created 
Info:        Working on 678
Info:            Created 
Info:        Working on 677
Info:            Created 
Info:        Working on 705
Info:            Created 
Info:        Working on 623
Info:            Created 
Info:        Working on 535
Info:            Created 
Info:        Working on 524
Info:            Created 
Info:        Working on 671
Info:            Created 
Info:        Working on 749
Info:            Created 
Info:        Working on 681
Info:            Created 
Info:        Working on 752
Info:            Created 
Info:        Working on 817
Info:            Created 
Info:        Working on 484
Info:            Created 
Info:        Working on 352
Info:            Created 
Info:        Working on 443
Info:            Created 
Info:        Working on 534
Info:            Created 
Info:        Working on 565
Info:            Created 
Info:        Working on 542
Info:            Created 
Info:        Working on 359
Info:            Created 
Info:        Working on 541
Info:            Created 
Info:        Working on 560
Info:            Created 
Info:        Working on 420
Info:            Created 
Info:        Working on 266
Info:            Created 
Info:        Working on 452
Info:            Created 
Info:        Working on 524
Info:            Created 
Info:        Working on 49
Info:            Created 
Info:        Working on 255
Info:            Created 
Info:        Working on 731
Info:            Created 
Info:        Working on 345
Info:            Created 
Info:        Working on 439
Info:            Created 
Info:        Working on 822
Info:            Created 
Info:        Working on 527
Info:            Created 
Info:        Working on 616
Info:            Created 
Info:        Working on 690
Info:            Created 
Info:        Working on 690
Info:            Created 
Info:        Working on 652
Info:            Created 
Info:        Working on 894
Info:            Created 
Info:        Working on 984
Info:            Created 
Info:        Working on 728
Info:            Created 
Info:        Working on 985
Info:            Created 
Info:        Working on 794
Info:            Created 
Info:        Working on 797
Info:            Created 
Info:        Working on 558
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 8.88178e-016
Info:            Rough distance of curve to surface: 1.42386e-014
Info:            Rough distance of curve to surface: 1.42386e-014
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.83103e-015
Info:            Rough distance of curve to surface: 2.80867e-015
Info:            Rough distance of curve to surface: 2.66454e-015
Info:            Rough distance of curve to surface: 3.58036e-015
Info:            Rough distance of curve to surface: 2.66454e-015
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.42386e-014
Info:            Rough distance of curve to surface: 8.88178e-016
Info:            Rough distance of curve to surface: 1.42386e-014
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.33227e-015
Info:            Rough distance of curve to surface: 8.88178e-016
Info:            Rough distance of curve to surface: 1.46751e-014
Info:            Rough distance of curve to surface: 1.46751e-014
Info:            Rough distance of curve to surface: 1.98603e-015
Info:            Rough distance of curve to surface: 1.42178e-014
Info:            Rough distance of curve to surface: 4.44089e-016
Info:        Distance between segments 6.12323e-016
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 7.16072e-015
Info:        Distance between segments 3.42361e-009
Info:              Tweaking curve ends
Info:            Distances between ends and compromise: 1.7118e-009, 1.7118e-009
Info:        Distance between segments 1.79018e-015
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.81908e-016
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.36468e-016
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.77662e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.77739e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 9.54207e-016
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.24302e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Singularity found at u = 0, v = [0, 1], width = 3.55271e-015
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.21254e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.98603e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Singularity found at u = 1, v = [0, 1], width = 7.10543e-015
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.84908e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.60119e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 5.32907e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.63993e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.57145e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.09836e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.91287e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.5224e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.02044e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.00486e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.19948e-015
Info:            Rough distance of curve to surface: 7.11948e-015
Info:        Distance between segments 7.83976e-016
Info:        Distance between segments 7.83976e-016
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.00486e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Singularity found at u = 0, v = [0, 1], width = 7.67217e-014
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.10543e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.42419e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.00486e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.00551e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Singularity found at u = 0, v = [0, 1], width = 7.7123e-014
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.9443e-031
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.16727e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.94411e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.94411e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.00486e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.28146e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Singularity found at u = 0, v = [0, 1], width = 9.1563e-014
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.94411e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.99947e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.10543e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.10543e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.00486e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.10543e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Singularity found at u = 0, v = [0, 1], width = 7.98731e-014
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.10543e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.46783e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.94411e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.94411e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.00486e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.94411e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Singularity found at u = 0, v = [0, 1], width = 7.70394e-014
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.77636e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.38412e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.32411e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.32411e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.00486e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.138e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.79515e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.11015e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.56215e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.56215e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.55271e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.11015e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.59084e-016
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.16455e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Singularity found at u = 0, v = [0, 1], width = 7.10543e-014
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.78009e-006
Info:            Rough distance greater than double tolerance.  Getting dropped distance.
Info:            Dropped distance of curve to surface: 7.78009e-006
Info:            Rough distance of curve to surface: 8.52802e-014
Info:            Rough distance of curve to surface: 1.48403e-005
Info:            Rough distance greater than double tolerance.  Getting dropped distance.
Info:            Dropped distance of curve to surface: 0.00012119
Info:            Rough distance of curve to surface: 2.72285e-005
Info:            Rough distance greater than double tolerance.  Getting dropped distance.
Info:            Dropped distance of curve to surface: 4.6054e-005
Info:            Rough distance of curve to surface: 1.70535e-013
Info:          Bumping 3D tolerance from 1e-006 to 0.000145428 for this trimmed surface
Info:        Distance between segments 1.55685e-014
Info:              Tweaking curve ends
Info:            Distances between ends and compromise: 7.95651e-015, 7.6404e-015
Info:        Distance between segments 2.20793e-011
Info:              Tweaking curve ends
Info:            Distances between ends and compromise: 1.10419e-011, 1.10374e-011
Info:        Distance between segments 9.05768e-015
Info:        Distance between segments 0
Info:        Distance between segments 4.05789e-011
Info:              Tweaking curve ends
Info:            Distances between ends and compromise: 2.02896e-011, 2.02893e-011
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.77636e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.32411e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.32411e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.00486e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 8.88915e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.32411e-015
Info:            Rough distance of curve to surface: 0.000289779
Info:            Rough distance greater than double tolerance.  Getting dropped distance.
Info:            Dropped distance of curve to surface: 0.000389377
Info:          Bumping 3D tolerance from 1e-006 to 0.000467252 for this trimmed surface
Info:        Distance between segments 0.000311605
Info:              Tweaking curve ends
Info:            Distances between ends and compromise: 0.000216503, 0.000129387
Info:        Distance between segments 0.000363106
Info:              Tweaking curve ends
Info:            Distances between ends and compromise: 0.000149066, 0.000255307
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.99361e-015
Info:            Rough distance of curve to surface: 0.000895115
Info:            Rough distance greater than double tolerance.  Getting dropped distance.
Info:            Dropped distance of curve to surface: 0.000895115
Info:          Bumping 3D tolerance from 1e-006 to 0.00107414 for this trimmed surface
Info:        Distance between segments 4.90478e-006
Info:              Tweaking curve ends
Info:            Distances between ends and compromise: 2.45239e-006, 2.45239e-006
Info:        Distance between segments 0.000206179
Info:              Tweaking curve ends
Info:            Distances between ends and compromise: 0.00010309, 0.00010309
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 0.000311605
Info:            Rough distance greater than double tolerance.  Getting dropped distance.
Info:            Dropped distance of curve to surface: 0.000311605
Info:            Rough distance of curve to surface: 8.2472e-013
Info:            Rough distance of curve to surface: 0.000363106
Info:            Rough distance greater than double tolerance.  Getting dropped distance.
Info:            Dropped distance of curve to surface: 0.000363106
Info:            Rough distance of curve to surface: 0.000316102
Info:            Rough distance greater than double tolerance.  Getting dropped distance.
Info:            Dropped distance of curve to surface: 0.000324467
Info:            Rough distance of curve to surface: 4.80382e-012
Info:            Rough distance of curve to surface: 0.000316102
Info:            Rough distance greater than double tolerance.  Getting dropped distance.
Info:            Dropped distance of curve to surface: 0.000324467
Info:            Rough distance of curve to surface: 5.79534e-005
Info:            Rough distance greater than double tolerance.  Getting dropped distance.
Info:            Dropped distance of curve to surface: 0.000548869
Info:            Rough distance of curve to surface: 8.426e-015
Info:          Bumping 3D tolerance from 1e-006 to 0.000658643 for this trimmed surface
Info:        Distance between segments 0.000206179
Info:              Tweaking curve ends
Info:            Distances between ends and compromise: 0.00010309, 0.00010309
Info:        Distance between segments 0.000311605
Info:              Tweaking curve ends
Info:            Distances between ends and compromise: 0.000311605, 3.29585e-014
Info:        Distance between segments 0.000363106
Info:              Tweaking curve ends
Info:            Distances between ends and compromise: 1.13e-011, 0.000363106
Info:        Distance between segments 7.32411e-015
Info:        Distance between segments 3.108e-016
Info:        Distance between segments 3.108e-016
Info:        Distance between segments 7.32411e-015
Info:        Distance between segments 4.90478e-006
Info:              Tweaking curve ends
Info:            Distances between ends and compromise: 2.45239e-006, 2.45239e-006
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.46482e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.94039e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.58036e-015
Info:            Rough distance of curve to surface: 3.58036e-015
Info:            Rough distance of curve to surface: 4.46304e-015
Info:            Rough distance of curve to surface: 4.44089e-015
Info:        Distance between segments 8.88178e-016
Info:        Distance between segments 0
Info:        Distance between segments 1.83103e-015
Info:        Distance between segments 4.44089e-016
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.16902e-010
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.83103e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.42109e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.46482e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.42155e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Singularity found at u = 0, v = [0, 1], width = 1.21893e-013
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.42109e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.43214e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.42109e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.71378e-016
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.77636e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.43214e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Singularity found at u = 0, v = [0, 1], width = 1.01529e-013
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.43214e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.5916e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.42109e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.42109e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.42109e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.58923e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Singularity found at u = 0, v = [0, 1], width = 1.26619e-013
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.55271e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.5916e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.78833e-017
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.42109e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.57083e-030
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.42155e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Singularity found at u = 0, v = [0, 1], width = 7.31624e-014
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.55271e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.67485e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.78833e-017
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.42109e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.55271e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.46527e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Singularity found at u = 0, v = [0, 1], width = 6.88136e-014
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.55271e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.67485e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.42109e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.42109e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.77636e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 8.88178e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Singularity found at u = 0, v = [0, 1], width = 6.87055e-014
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.77636e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.77637e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.10543e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.13163e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.94411e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.46527e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Singularity found at u = 0, v = [0, 1], width = 4.65145e-014
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.55271e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.67485e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.10553e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.42109e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.45124e-031
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.46527e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Singularity found at u = 0, v = [0, 1], width = 5.64537e-014
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.55271e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.16727e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.78833e-017
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.10543e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.73299e-030
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.55271e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Singularity found at u = 0, v = [0, 1], width = 4.5065e-014
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.32411e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.32411e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.10553e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.71378e-016
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.57061e-030
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.11464e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Singularity found at u = 0, v = [0, 1], width = 5.54054e-014
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.77636e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.77637e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.78833e-017
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.10543e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.63954e-030
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.46527e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Singularity found at u = 0, v = [0, 1], width = 4.66202e-014
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.94411e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.77637e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.10543e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.10543e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.77636e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 5.03731e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Singularity found at u = 0, v = [0, 1], width = 4.01477e-014
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 9.86076e-032
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.77637e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.55292e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.10543e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.72518e-030
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.11464e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Singularity found at u = 0, v = [0, 1], width = 5.21679e-014
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.55271e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.16727e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.55292e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.71378e-016
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.55271e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.5711e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Singularity found at u = 0, v = [0, 1], width = 2.74957e-014
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.97205e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.67485e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.00519e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.56215e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 5.03097e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.94833e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.56215e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.56215e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 5.03097e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.38147e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.94833e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.94833e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.94833e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.94833e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.94833e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.94833e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.10543e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.94833e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.00519e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.94833e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.94833e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.16455e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.43509e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.56215e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.46505e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.46505e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.46505e-014
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.86441e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.56215e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.92976e-014
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.55272e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.55271e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.77636e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 5.03731e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Singularity found at u = 0, v = [0, 1], width = 2.53e-014
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.77636e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.67485e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 0.000608406
Info:            Rough distance greater than double tolerance.  Getting dropped distance.
Info:            Dropped distance of curve to surface: 0.000608406
Info:          Bumping 3D tolerance from 1e-006 to 0.000730087 for this trimmed surface
Info:        Distance between segments 1.2326e-031
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.56215e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 0.00191992
Info:            Rough distance greater than double tolerance.  Getting dropped distance.
Info:            Dropped distance of curve to surface: 0.00238899
Info:            Rough distance of curve to surface: 1.77636e-015
Info:            Rough distance of curve to surface: 7.6404e-015
Info:            Rough distance of curve to surface: 3.55271e-015
Info:            Rough distance of curve to surface: 1.43907e-011
Info:          Bumping 3D tolerance from 1e-006 to 0.00286679 for this trimmed surface
Info:        Distance between segments 0.00209991
Info:              Tweaking curve ends
Info:            Distances between ends and compromise: 0.000425313, 0.00196646
Info:        Distance between segments 8.88178e-016
Info:        Distance between segments 7.16072e-015
Info:        Distance between segments 3.76822e-015
Info:        Distance between segments 4.07014e-015
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.37776e-015
Info:            Rough distance of curve to surface: 7.10543e-015
Info:            Rough distance of curve to surface: 7.99361e-015
Info:            Rough distance of curve to surface: 7.99361e-015
Info:        Distance between segments 0
Info:        Distance between segments 3.66205e-015
Info:        Distance between segments 9.93014e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.16072e-015
Info:            Rough distance of curve to surface: 1.46436e-015
Info:            Rough distance of curve to surface: 7.11929e-015
Info:            Rough distance of curve to surface: 7.32411e-015
Info:        Distance between segments 5.40258e-015
Info:        Distance between segments 6.12323e-016
Info:        Distance between segments 3.02013e-015
Info:        Distance between segments 3.42361e-009
Info:              Tweaking curve ends
Info:            Distances between ends and compromise: 1.71181e-009, 1.71181e-009
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.76822e-015
Info:            Rough distance of curve to surface: 3.76822e-015
Info:            Rough distance of curve to surface: 3.55271e-015
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.43922e-011
Info:            Rough distance of curve to surface: 3.66205e-015
Info:            Rough distance of curve to surface: 7.37776e-015
Info:            Rough distance of curve to surface: 3.66205e-015
Info:            Rough distance of curve to surface: 0.00190556
Info:            Rough distance greater than double tolerance.  Getting dropped distance.
Info:            Dropped distance of curve to surface: 0.00236681
Info:          Bumping 3D tolerance from 1e-006 to 0.00284017 for this trimmed surface
Info:        Distance between segments 0.00207778
Info:              Tweaking curve ends
Info:            Distances between ends and compromise: 0.00195004, 0.000414137
Info:        Distance between segments 4.07014e-015
Info:        Distance between segments 4.07014e-015
Info:        Distance between segments 7.16072e-015
Info:        Distance between segments 8.88178e-016
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.42663e-014
Info:            Rough distance of curve to surface: 7.17448e-015
Info:            Rough distance of curve to surface: 9.93014e-016
Info:            Rough distance of curve to surface: 7.16072e-015
Info:        Distance between segments 6.12323e-016
Info:        Distance between segments 1.32037e-014
Info:              Tweaking curve ends
Info:            Distances between ends and compromise: 7.5886e-015, 5.61733e-015
Info:        Distance between segments 3.42361e-009
Info:              Tweaking curve ends
Info:            Distances between ends and compromise: 1.71181e-009, 1.71181e-009
Info:        Distance between segments 1.25607e-015
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.76822e-015
Info:            Rough distance of curve to surface: 3.76822e-015
Info:            Rough distance of curve to surface: 3.76822e-015
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.16852e-015
Info:            Rough distance of curve to surface: 1.69357e-015
Info:            Rough distance of curve to surface: 7.5886e-015
Info:            Rough distance of curve to surface: 7.6404e-015
Info:            Rough distance of curve to surface: 3.66205e-015
Info:            Rough distance of curve to surface: 3.98609e-015
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 1.52032e-014
Info:              Tweaking curve ends
Info:            Distances between ends and compromise: 7.94411e-015, 7.37776e-015
Info:        Distance between segments 3.1137e-014
Info:              Tweaking curve ends
Info:            Distances between ends and compromise: 1.5913e-014, 1.52808e-014
Info:        Distance between segments 4.07014e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.5886e-015
Info:            Rough distance of curve to surface: 2.66454e-015
Info:            Rough distance of curve to surface: 4.07014e-015
Info:            Rough distance of curve to surface: 7.79373e-015
Info:            Rough distance of curve to surface: 1.58882e-014
Info:            Rough distance of curve to surface: 7.5886e-015
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 4.07014e-015
Info:        Distance between segments 1.46482e-014
Info:              Tweaking curve ends
Info:            Distances between ends and compromise: 7.32411e-015, 7.32411e-015
Info:        Distance between segments 1.00878e-014
Info:              Tweaking curve ends
Info:            Distances between ends and compromise: 8.14029e-015, 3.20237e-015
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67598e-011
Info:            Rough distance of curve to surface: 4.67605e-011
Info:            Rough distance of curve to surface: 4.67603e-011
Info:            Rough distance of curve to surface: 3.42361e-009
Info:        Distance between segments 3.42361e-009
Info:              Tweaking curve ends
Info:            Distances between ends and compromise: 1.71181e-009, 1.71181e-009
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 3.42361e-009
Info:              Tweaking curve ends
Info:            Distances between ends and compromise: 1.7118e-009, 1.7118e-009
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.67599e-011
Info:            Rough distance of curve to surface: 4.67606e-011
Info:            Rough distance of curve to surface: 4.67599e-011
Info:            Rough distance of curve to surface: 3.42361e-009
Info:        Distance between segments 3.4236e-009
Info:              Tweaking curve ends
Info:            Distances between ends and compromise: 1.7118e-009, 1.7118e-009
Info:        Distance between segments 2.22045e-016
Info:        Distance between segments 0
Info:        Distance between segments 3.42361e-009
Info:              Tweaking curve ends
Info:            Distances between ends and compromise: 1.71181e-009, 1.71181e-009
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.95129e-012
Info:            Rough distance of curve to surface: 4.44089e-015
Info:            Rough distance of curve to surface: 2.51215e-015
Info:            Rough distance of curve to surface: 0.00131257
Info:            Rough distance greater than double tolerance.  Getting dropped distance.
Info:            Dropped distance of curve to surface: 0.00221766
Info:            Rough distance of curve to surface: 2.82577e-012
Info:            Rough distance of curve to surface: 1.33747e-013
Info:            Rough distance of curve to surface: 7.2156e-015
Info:          Bumping 3D tolerance from 1e-006 to 0.00266119 for this trimmed surface
Info:        Distance between segments 8.88178e-016
Info:        Distance between segments 3.55271e-015
Info:        Distance between segments 3.20237e-015
Info:        Distance between segments 5.61733e-015
Info:        Distance between segments 0.00209991
Info:              Tweaking curve ends
Info:            Distances between ends and compromise: 0.00154708, 0.000819801
Info:        Distance between segments 9.27285e-015
Info:        Distance between segments 8.84841e-015
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.59872e-014
Info:            Rough distance of curve to surface: 1.55875e-014
Info:            Rough distance of curve to surface: 2.94772e-012
Info:            Rough distance of curve to surface: 8.15239e-015
Info:            Rough distance of curve to surface: 1.34652e-013
Info:            Rough distance of curve to surface: 2.82973e-012
Info:            Rough distance of curve to surface: 0.00128674
Info:            Rough distance greater than double tolerance.  Getting dropped distance.
Info:            Dropped distance of curve to surface: 0.00217143
Info:          Bumping 3D tolerance from 1e-006 to 0.00260571 for this trimmed surface
Info:        Distance between segments 7.94411e-015
Info:        Distance between segments 1.98603e-015
Info:        Distance between segments 1.44585e-014
Info:              Tweaking curve ends
Info:            Distances between ends and compromise: 7.32411e-015, 7.16072e-015
Info:        Distance between segments 1.56443e-014
Info:              Tweaking curve ends
Info:            Distances between ends and compromise: 8.00593e-015, 7.6404e-015
Info:        Distance between segments 1.77636e-015
Info:        Distance between segments 1.64013e-014
Info:              Tweaking curve ends
Info:            Distances between ends and compromise: 8.56528e-015, 7.94411e-015
Info:        Distance between segments 0.00207778
Info:              Tweaking curve ends
Info:            Distances between ends and compromise: 0.000815708, 0.00152351
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.10543e-015
Info:            Rough distance of curve to surface: 7.16072e-015
Info:            Rough distance of curve to surface: 7.16072e-015
Info:            Rough distance of curve to surface: 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.10543e-015
Info:            Rough distance of curve to surface: 8.88178e-016
Info:            Rough distance of curve to surface: 7.16072e-015
Info:            Rough distance of curve to surface: 7.16072e-015
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 8.14029e-015
Info:            Rough distance of curve to surface: 7.53644e-015
Info:            Rough distance of curve to surface: 7.10543e-015
Info:            Rough distance of curve to surface: 7.53644e-015
Info:        Distance between segments 8.88178e-016
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 5.40258e-015
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 8.88178e-016
Info:            Rough distance of curve to surface: 1.42542e-014
Info:            Rough distance of curve to surface: 2.84391e-014
Info:            Rough distance of curve to surface: 8.88178e-016
Info:            Rough distance of curve to surface: 1.46751e-014
Info:            Rough distance of curve to surface: 1.42109e-014
Info:            Rough distance of curve to surface: 1.42109e-014
Info:        Distance between segments 0
Info:        Distance between segments 6.12323e-016
Info:        Distance between segments 8.88178e-016
Info:        Distance between segments 3.42361e-009
Info:              Tweaking curve ends
Info:            Distances between ends and compromise: 1.7118e-009, 1.7118e-009
Info:        Distance between segments 7.5886e-015
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.5913e-014
Info:            Rough distance of curve to surface: 2.13348e-014
Info:            Rough distance of curve to surface: 1.44312e-014
Info:            Rough distance of curve to surface: 2.85602e-014
Info:            Rough distance of curve to surface: 2.51215e-015
Info:            Rough distance of curve to surface: 2.8491e-014
Info:            Rough distance of curve to surface: 1.44312e-014
Info:            Rough distance of curve to surface: 2.14086e-014
Info:            Rough distance of curve to surface: 1.52032e-014
Info:            Rough distance of curve to surface: 1.46751e-014
Info:            Rough distance of curve to surface: 1.78079e-014
Info:            Rough distance of curve to surface: 1.78079e-014
Info:            Rough distance of curve to surface: 1.78079e-014
Info:            Rough distance of curve to surface: 1.78079e-014
Info:            Rough distance of curve to surface: 2.13902e-014
Info:        Distance between segments 7.16072e-015
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 7.16072e-015
Info:        Distance between segments 3.76822e-015
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 4.07014e-015
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.66081e-013
Info:            Rough distance of curve to surface: 3.65227e-013
Info:            Rough distance of curve to surface: 3.6518e-013
Info:            Rough distance of curve to surface: 3.65658e-013
Info:            Rough distance of curve to surface: 3.62785e-013
Info:        Distance between segments 3.02013e-015
Info:        Distance between segments 1.33227e-015
Info:        Distance between segments 1.79018e-015
Info:        Distance between segments 1.55431e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.42241e-007
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.22465e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.99976e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.79515e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.55875e-015
Info:            Rough distance of curve to surface: 1.5363e-013
Info:            Rough distance of curve to surface: 3.97745e-015
Info:            Rough distance of curve to surface: 6.47527e-013
Info:        Distance between segments 3.63374e-016
Info:        Distance between segments 1.77664e-015
Info:        Distance between segments 3.55285e-015
Info:        Distance between segments 3.63374e-016
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.88181e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 4.09696e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 0.000918913
Info:            Rough distance greater than double tolerance.  Getting dropped distance.
Info:            Dropped distance of curve to surface: 0.00130744
Info:          Bumping 3D tolerance from 1e-006 to 0.00156893 for this trimmed surface
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.83103e-015
Info:            Rough distance of curve to surface: 1.83103e-015
Info:        Distance between segments 0
Info:        Distance between segments 1.33227e-015
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.03507e-015
Info:            Rough distance of curve to surface: 2.03507e-015
Info:        Distance between segments 4.44089e-016
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Singularity found at u = 1, v = [0, 1], width = 8.52651e-014
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.32747e-015
Info:            Rough distance of curve to surface: 3.66952e-015
Info:            Rough distance of curve to surface: 3.66952e-015
Info:            Rough distance of curve to surface: 3.66952e-015
Info:            Rough distance of curve to surface: 7.16072e-015
Info:            Rough distance of curve to surface: 7.36367e-015
Info:        Distance between segments 4.52884e-015
Info:        Distance between segments 6.12323e-016
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 6.12323e-016
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Singularity found at u = 0, v = [0, 1], width = 7.10543e-014
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.71289e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.07598e-012
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.43216e-014
Info:            Rough distance of curve to surface: 1.43467e-014
Info:        Distance between segments 7.83976e-016
Info:        Distance between segments 7.83976e-016
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.169e-010
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 7.13176e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.06162e-016
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.80794e-015
Info:        Distance between segments 0
Info:        Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.10355e-014
Info:            Rough distance of curve to surface: 3.02633e-014
Info:            Rough distance of curve to surface: 3.11876e-014
Info:            Rough distance of curve to surface: 3.11876e-014
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 3.75786e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.51282e-015
Info:        Distance between segments 0
Info:    Working on 1
Info:        Working on 151
Info:            Created 
Info:        Working on 152
Info:            Created 
Error:       Unable to make face #15
Info:        Working on 205
Info:            Created 
Info:        Working on 206
Info:            Created 
Error:       Unable to make face #19
Info:        Working on 277
Info:            Created 
Error:       Unable to make face #26
Error:       Unable to make face #38
Info:        Working on 296
Info:            Created 
Info:        Working on 369
Info:            Created 
Error:       Unable to make face #66
Error:       Unable to make face #115
Info:        Working on 217
Info:            Created 
Info:        Working on 213
Info:            Created 
Error:       Unable to make face #182
Error:       Unable to make face #216
Error:       Unable to make face #150
Info:        Working on 459
Info:            Created 
Info:        Working on 630
Info:            Created 
Info:        Working on 300
Info:            Created 
Error:       Unable to create brep
Info:        Creating exploded open shell B-rep from working faces
Info:        Created 
Info:    Working on BRep 1
Info:        In fallback path: Trying to create B-rep face
Info:        Trying model space trim
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 1.88194e-015
Info:        Distance between segments 0
Info:        Distance of curves to surface:
Info:            Rough distance of curve to surface: 2.02402e-015
Info:        Distance between segments 0
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  2 found       2 created       0 failed
Finished logging messages at Tue May 28 16:04:18 2019
